"""
src/matcher.py
==============
Match Engine — compares a candidate profile against a job offer and produces
a structured ``MatchReport`` using the OpenAI Structured Outputs API.
"""

from __future__ import annotations

import json
import logging
import os

from openai import OpenAI

from src.models import CandidateData, JobOfferData, MatchReport

logger = logging.getLogger(__name__)

_MATCH_SYSTEM_PROMPT = """\
Jesteś rygorystycznym analitykiem rekrutacyjnym. Twoim zadaniem jest precyzyjne porównanie \
profilu kandydata z wymaganiami oferty pracy i wygenerowanie ustrukturyzowanego raportu.

Zasady oceniania:
- Porównuj RYGORYSTYCZNIE umiejętności twarde (`umiejetnosci_twarde`) kandydata \
z wymaganiami oferty. Każda umiejętność musi być jawnie potwierdzona w profilu kandydata — \
nie zakładaj, że kandydat ją posiada bez dowodu.
- Uwzględniaj poziom stanowiska i lata doświadczenia przy obliczaniu procentu dopasowania.
- `procent_dopasowania` to liczba całkowita 0–100 odzwierciedlająca ogólne pokrycie wymagań.
- `spelnione_wymagania` — lista wymagań z oferty, które kandydat ewidentnie spełnia.
- `brakujace_wymagania` — lista wymagań z oferty, których kandydat NIE spełnia lub \
brak ich potwierdzenia w profilu.
- `rekomendacje_zmian_w_cv` — konkretne, praktyczne porady co dodać lub zmienić w CV \
kandydata, by lepiej dopasować się do tej oferty. Minimum 2 rekomendacje.
- Pisz po polsku.
"""


class SkillMatcher:
    """
    Compares a :class:`CandidateData` profile against a :class:`JobOfferData`
    and returns a :class:`MatchReport` generated by an LLM.

    Parameters
    ----------
    model:
        OpenAI model identifier.  Defaults to ``"gpt-4o-mini"``.

    Raises
    ------
    ValueError
        If the ``OPENAI_API_KEY`` environment variable is not set.
    """

    def __init__(self, model: str = "gpt-4o-mini") -> None:
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            raise ValueError(
                "OPENAI_API_KEY environment variable is not set. "
                "Create a .env file with OPENAI_API_KEY=<your-key> and load it "
                "before constructing SkillMatcher."
            )
        self._model = model
        self._client = OpenAI(api_key=api_key)
        logger.info("SkillMatcher initialized with model=%s", model)

    def compare(self, candidate: CandidateData, job: JobOfferData) -> MatchReport:
        """
        Compare *candidate* against *job* and return a structured match report.

        Both objects are serialised to JSON and sent to the LLM as the user
        message.  The model is instructed via the system prompt to fill every
        field of :class:`MatchReport`.

        Parameters
        ----------
        candidate:
            Structured candidate profile extracted from the CV.
        job:
            Structured job requirements extracted from the offer.

        Returns
        -------
        MatchReport
            Pydantic model with match score, met/missing requirements and CV
            improvement tips.

        Raises
        ------
        RuntimeError
            If the API call fails or the model returns no structured response.
        """
        user_content = (
            "## Profil kandydata\n"
            f"{json.dumps(candidate.model_dump(), ensure_ascii=False, indent=2)}\n\n"
            "## Wymagania oferty pracy\n"
            f"{json.dumps(job.model_dump(), ensure_ascii=False, indent=2)}"
        )

        logger.debug("Requesting MatchReport from LLM.")

        try:
            response = self._client.beta.chat.completions.parse(
                model=self._model,
                messages=[
                    {"role": "system", "content": _MATCH_SYSTEM_PROMPT},
                    {"role": "user", "content": user_content},
                ],
                response_format=MatchReport,
            )
        except Exception as exc:
            raise RuntimeError(f"OpenAI API call failed: {exc}") from exc

        parsed = response.choices[0].message.parsed
        if parsed is None:
            raise RuntimeError(
                "OpenAI returned a refusal or could not produce a structured response. "
                f"Finish reason: {response.choices[0].finish_reason}"
            )

        logger.debug(
            "MatchReport generated — procent_dopasowania=%d%%", parsed.procent_dopasowania
        )
        return parsed
